INSERT INTO pravoberega.Club VALUES(001, 'Военмех');
INSERT INTO pravoberega.Club VALUES(002, 'Локомотив');
INSERT INTO pravoberega.Club VALUES(003, 'Феникс');
INSERT INTO pravoberega.Club VALUES(004, 'Союз');
INSERT INTO pravoberega.Club VALUES(005, 'Ленинградская  семья');
INSERT INTO pravoberega.Club VALUES(006, 'Царское Село');
INSERT INTO pravoberega.Club VALUES(007, 'Антарес');
INSERT INTO pravoberega.Club VALUES(008, 'Северина');
INSERT INTO pravoberega.Club VALUES(009, 'Кикэмоллочка');
INSERT INTO pravoberega.Club VALUES(010, 'Юана-спорт');
INSERT INTO pravoberega.Club VALUES(011, 'Звезда');
INSERT INTO pravoberega.Club VALUES(012, 'ОмегаПРО');
INSERT INTO pravoberega.Club VALUES(013, 'ДиЛайф');
INSERT INTO pravoberega.Club VALUES(014, 'Феникс-ТитанБанк');
INSERT INTO pravoberega.Club VALUES(015, 'Грифон');
INSERT INTO pravoberega.Club VALUES(016, 'Бутса');
INSERT INTO pravoberega.Club VALUES(017, 'Белуга');
INSERT INTO pravoberega.Club VALUES(018, 'Фортуна');
INSERT INTO pravoberega.Club VALUES(019, 'Доты');
INSERT INTO pravoberega.Club VALUES(020, 'Ильницкий Недвижимость');
INSERT INTO pravoberega.Club VALUES(021, 'Дети Гужи');
INSERT INTO pravoberega.Club VALUES(022, 'Урицк');
INSERT INTO pravoberega.Club VALUES(023, 'Ока');
INSERT INTO pravoberega.Club VALUES(024, 'Центр Сити');
INSERT INTO pravoberega.Club VALUES(025, 'Торнадо');
INSERT INTO pravoberega.Club VALUES(026, 'Эскада');
INSERT INTO pravoberega.Club VALUES(027, 'Марвел');
INSERT INTO pravoberega.Club VALUES(028, 'Проект Дичь');
INSERT INTO pravoberega.Club VALUES(029, 'РГПУ им. Герцена');
INSERT INTO pravoberega.Club VALUES(030, 'Небойсяспорта');
INSERT INTO pravoberega.Club VALUES(031, 'Футболика');
INSERT INTO pravoberega.Club VALUES(032, 'Демоны');
INSERT INTO pravoberega.Club VALUES(033, 'Суета');
INSERT INTO pravoberega.Club VALUES(034, 'Малоохтинский колледж');
INSERT INTO pravoberega.Club VALUES(035, 'Атланта');
